### ISSUE TITLE
Fails to build with GDAL 2.0

### ISSUE THREAD

**Issue by sebastic** [tudelft3d/pprepair#29]
As reported in [Debian Bug #802495](https://bugs.debian.org/802495), pprepair fails to build with GDAL 2.0:
```
  error: 'Open' is not a member of 'OGRSFDriverRegistrar'
  error: 'class GDALDriver' has no member named 'GetName'
  error: invalid conversion from 'GDALDriver*' to 'OGRSFDriver*'
```
The full build log is attached to the bugreport, which GitHub didn't allow me to do here:
[pprepair_0.0~20150323-6284890-2_gdal-2.0.log](https://bugs.debian.org/cgi-bin/bugreport.cgi?filename=pprepair_0.0~20150323-6284890-2_gdal-2.0.log;att=1;msg=5;bug=802495)

pprepair needs to be patched to support GDAL 2.0,
please refer to the [MIGRATION GUIDE FROM GDAL 1.11 to GDAL 2.0](https://svn.osgeo.org/gdal/branches/2.0/gdal/MIGRATION_GUIDE.TXT) for pointers.
